"use client";
import {useEffect,useMemo,useState} from 'react';
type Lead={id:string;name?:string;phone?:string;email?:string;status:string;lead_score:number;temperature?:string;last_seen_at:string;last_request?:string;summary?:string;next_best_action?:string;next_action_at?:string;desired_models?:string[];desired_exterior?:string[];desired_interior?:string[];budget_max?:number;notes?:string;transcript?:any[];timeframe?:string;trade_in?:boolean;};
type Detail={activities:any[];tasks:any[];interests:any[];matches:any[];appointments:any[]};
const stages=['new','contacted','qualified','appointment','working','sold','nurture','lost'];
function who(l:Lead){return l.name||l.phone||l.email||'Anonymous shopper'}
function timeAgo(d:string){const s=Math.max(1,Math.floor((Date.now()-new Date(d).getTime())/1000));if(s<60)return `${s}s ago`;if(s<3600)return `${Math.floor(s/60)}m ago`;if(s<86400)return `${Math.floor(s/3600)}h ago`;return `${Math.floor(s/86400)}d ago`;}
export default function CRM(){const[leads,setLeads]=useState<Lead[]>([]),[selected,setSelected]=useState<Lead|null>(null),[detail,setDetail]=useState<Detail|null>(null),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[error,setError]=useState(''),[view,setView]=useState<'today'|'leads'|'pipeline'>('today'),[ai,setAi]=useState<any>(null),[aiLoading,setAiLoading]=useState(false),[taskTitle,setTaskTitle]=useState('Follow up');
async function load(){const p=new URLSearchParams();if(q)p.set('q',q);if(status!=='all')p.set('status',status);const r=await fetch(`/api/crm?${p}`,{cache:'no-store'});const d=await r.json();if(!r.ok){setError(d.error);return}setLeads(d.leads||[]);setError('');}
async function openLead(l:Lead){setSelected(l);setAi(null);const r=await fetch(`/api/crm/detail?id=${l.id}`,{cache:'no-store'});const d=await r.json();setDetail(d);if(d.lead)setSelected(d.lead);}
useEffect(()=>{load()},[status]);
async function save(patch:Partial<Lead>){if(!selected)return;const r=await fetch('/api/crm',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,...patch})});const d=await r.json();if(d.lead){setSelected(d.lead);setLeads(x=>x.map(l=>l.id===d.lead.id?d.lead:l));}}
async function copilot(){if(!selected)return;setAiLoading(true);const r=await fetch('/api/crm/copilot',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lead:selected})});const d=await r.json();setAiLoading(false);if(r.ok){setAi(d);await save({summary:d.summary,lead_score:d.score,temperature:d.temperature,next_best_action:d.next_best_action});}}
async function addTask(){if(!selected||!taskTitle.trim())return;await fetch('/api/crm/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'task',lead_id:selected.id,title:taskTitle,priority:'high'})});setTaskTitle('Follow up');openLead(selected);}
async function toggleTask(id:string,completed:boolean){await fetch('/api/crm/action',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'task',id,completed})});if(selected)openLead(selected);}
const stats=useMemo(()=>({hot:leads.filter(x=>x.temperature==='hot'||x.lead_score>=75).length,appointments:leads.filter(x=>x.status==='appointment').length,open:leads.filter(x=>!['sold','lost'].includes(x.status)).length,overdue:leads.filter(x=>x.next_action_at&&new Date(x.next_action_at)<new Date()&&!['sold','lost'].includes(x.status)).length}),[leads]);
const priority=useMemo(()=>[...leads].filter(x=>!['sold','lost'].includes(x.status)).sort((a,b)=>(b.lead_score||0)-(a.lead_score||0)).slice(0,12),[leads]);
const grouped=useMemo(()=>Object.fromEntries(stages.map(s=>[s,leads.filter(l=>l.status===s)])),[leads]);
return <main className="crm"><header className="crmNav"><div className="crmBrand"><b>JON ROVER</b><span>INTELLIGENCE CRM</span></div><nav><button className={view==='today'?'active':''} onClick={()=>setView('today')}>TODAY</button><button className={view==='leads'?'active':''} onClick={()=>setView('leads')}>LEADS</button><button className={view==='pipeline'?'active':''} onClick={()=>setView('pipeline')}>PIPELINE</button></nav><a href="/">LIVE SITE ↗</a></header><section className="crmHero"><div><span>YOUR SALES COMMAND CENTER</span><h1>Know who to call.<br/>Know what to say.</h1><p>Every shopper ranked by intent, context, timing and fit — with the next move ready.</p></div><div className="crmStats"><article><strong>{stats.hot}</strong><span>HOT NOW</span></article><article><strong>{stats.appointments}</strong><span>APPOINTMENTS</span></article><article><strong>{stats.overdue}</strong><span>NEEDS ACTION</span></article><article><strong>{stats.open}</strong><span>ACTIVE</span></article></div></section>
<section className="crmToolbar"><div className="crmSearch"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search a customer, model, budget, phone…"/><button onClick={load}>SEARCH →</button></div><div className="crmFilter"><button className={status==='all'?'active':''} onClick={()=>setStatus('all')}>ALL</button>{['new','qualified','appointment','working','nurture'].map(s=><button className={status===s?'active':''} key={s} onClick={()=>setStatus(s)}>{s.toUpperCase()}</button>)}</div></section>
{view==='pipeline'?<section className="crmPipeline">{stages.slice(0,6).map(stage=><div className="crmColumn" key={stage}><div className="crmColumnHead"><span>{stage.toUpperCase()}</span><b>{grouped[stage]?.length||0}</b></div>{(grouped[stage]||[]).map(l=><button key={l.id} className="crmPipelineCard" onClick={()=>openLead(l)}><div><span className={`crmDot ${l.temperature||''}`}/><b>{who(l)}</b><strong>{l.lead_score}</strong></div><p>{l.last_request||'Browsing inventory'}</p><small>{timeAgo(l.last_seen_at)}</small></button>)}</div>)}</section>:<section className="crmWorkspace"><aside className="crmRail"><div className="crmRailTitle">{view==='today'?'PRIORITY QUEUE':'ALL OPPORTUNITIES'}</div><p>{view==='today'?'Highest-intent customers first.':'Every active lead in one place.'}</p><div className="crmLegend"><span><i className="hot"/>HOT</span><span><i className="warm"/>WARM</span><span><i/>COLD</span></div></aside><div className="crmList"><div className="crmListHead"><span>SCORE</span><span>CUSTOMER</span><span>SHOPPING SIGNAL</span><span>NEXT MOVE</span><span>STATUS</span></div>{error?<div className="crmEmpty">{error}</div>:(view==='today'?priority:leads).length===0?<div className="crmEmpty">No leads yet. Concierge conversations will appear here automatically.</div>:(view==='today'?priority:leads).map(l=><button className={`crmLead ${selected?.id===l.id?'active':''}`} onClick={()=>openLead(l)} key={l.id}><span className={`crmScore ${l.temperature||''}`}>{l.lead_score}</span><span><b>{who(l)}</b><small>{timeAgo(l.last_seen_at)}</small></span><span><b>{l.last_request||l.desired_models?.join(', ')||'Browsing inventory'}</b><small>{l.budget_max?`Up to $${l.budget_max.toLocaleString()}`:'Budget not captured'}{l.timeframe?` · ${l.timeframe}`:''}</small></span><span><b>{l.next_best_action||'Review and follow up'}</b><small>{l.phone?'Text ready':'Contact info incomplete'}</small></span><span className="crmStatus">{l.status}</span></button>)}</div></section>}
{selected&&<aside className="crmDetail"><div className="crmDetailTop"><button className="crmClose" onClick={()=>{setSelected(null);setDetail(null)}}>×</button><span className="crmLabel">CUSTOMER INTELLIGENCE</span><h2>{who(selected)}</h2><p className="crmContact">{selected.phone||''}{selected.phone&&selected.email?' · ':''}{selected.email||''}</p><div className="crmBigScore"><strong>{selected.lead_score}</strong><span>BUYING<br/>INTENT</span><i className={selected.temperature||''}>{(selected.temperature||'cold').toUpperCase()}</i></div></div><div className="crmDetailScroll"><div className="crmInsight"><span>AI BRIEF</span><p>{selected.summary||selected.last_request||'Not enough information yet.'}</p></div><div className="crmInsight action"><span>NEXT BEST ACTION</span><p>{selected.next_best_action||'Review the conversation and make personal contact.'}</p></div><button className="crmAiButton" onClick={copilot} disabled={aiLoading}>{aiLoading?'ANALYZING…':'REFRESH AI STRATEGY ✦'}</button>{ai&&<div className="crmDraft"><span>READY-TO-SEND TEXT</span><p>{ai.draft_text}</p>{selected.phone&&<a href={`sms:${selected.phone}?body=${encodeURIComponent(ai.draft_text)}`}>OPEN IN MESSAGES →</a>}</div>}<div className="crmFacts"><span>{selected.desired_models?.join(', ')||'MODEL UNKNOWN'}</span><span>{selected.budget_max?`$${selected.budget_max.toLocaleString()} MAX`:'BUDGET UNKNOWN'}</span><span>{selected.trade_in?'HAS TRADE':'TRADE UNKNOWN'}</span></div><label>PIPELINE<select value={selected.status} onChange={e=>save({status:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></label><div className="crmTaskComposer"><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="Add a follow-up task"/><button onClick={addTask}>ADD</button></div>{detail?.tasks?.length?<div className="crmMiniSection"><span>FOLLOW-UP</span>{detail.tasks.map((t:any)=><label className="crmTask" key={t.id}><input type="checkbox" checked={Boolean(t.completed_at)} onChange={e=>toggleTask(t.id,e.target.checked)}/><b>{t.title}</b></label>)}</div>:null}{detail?.interests?.length?<div className="crmMiniSection"><span>VEHICLE INTEREST</span>{detail.interests.slice(0,5).map((v:any)=><div className="crmInterest" key={v.id}><b>{v.title||v.vin}</b><small>{v.action} · score {v.score||0}</small></div>)}</div>:null}<label>PRIVATE NOTES<textarea defaultValue={selected.notes||''} onBlur={e=>save({notes:e.target.value})}/></label><div className="crmActions">{selected.phone&&<a className="crmPrimary" href={`sms:${selected.phone}`}>TEXT CUSTOMER →</a>}{selected.phone&&<a className="crmSecondary" href={`tel:${selected.phone}`}>CALL</a>}</div></div></aside>}</main>}
