"use client";
import "./crm.css";
import {useEffect,useMemo,useState} from 'react';
type Lead={id:string;name?:string;phone?:string;email?:string;status:string;lead_score:number;temperature?:string;last_seen_at:string;last_request?:string;summary?:string;next_best_action?:string;desired_models?:string[];budget_max?:number;transcript?:any[];};
function who(l:Lead){return l.name||l.phone||l.email||'Anonymous shopper'}
function timeAgo(d:string){const s=Math.max(1,Math.floor((Date.now()-new Date(d).getTime())/1000));if(s<60)return `${s}s ago`;if(s<3600)return `${Math.floor(s/60)}m ago`;if(s<86400)return `${Math.floor(s/3600)}h ago`;return `${Math.floor(s/86400)}d ago`;}
function pos(l:Lead,i:number,total:number){const score=Math.max(0,Math.min(100,l.lead_score||0));const radius=8+(100-score)*.38;const angle=((i/Math.max(total,1))*Math.PI*2)+(score*.071);return{left:`${50+Math.cos(angle)*radius}%`,top:`${50+Math.sin(angle)*radius}%`};}
export default function CRM(){const[leads,setLeads]=useState<Lead[]>([]),[selected,setSelected]=useState<Lead|null>(null),[view,setView]=useState<'radar'|'chats'|'leads'>('radar'),[error,setError]=useState('');
async function load(){const r=await fetch('/api/crm',{cache:'no-store'});const d=await r.json();if(!r.ok){setError(d.error);return}setLeads(d.leads||[]);setError('');}
useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
const ranked=useMemo(()=>[...leads].sort((a,b)=>(b.lead_score||0)-(a.lead_score||0)),[leads]);const hot=ranked.filter(l=>l.lead_score>=75).length;const active=ranked.filter(l=>Date.now()-new Date(l.last_seen_at).getTime()<15*60*1000).length;
return <main className="crm"><header className="crmNav"><div className="crmBrand"><b>JON ROVER</b><span>INTELLIGENCE CRM</span></div><nav><button className={view==='radar'?'active':''} onClick={()=>setView('radar')}>ORBIT</button><button className={view==='chats'?'active':''} onClick={()=>setView('chats')}>LIVE CHATS</button><button className={view==='leads'?'active':''} onClick={()=>setView('leads')}>LEADS</button></nav><a href="/">LIVE SITE ↗</a></header><section className="crmHero"><div><span>REAL-TIME BUYING INTELLIGENCE</span><h1>See intent<br/>before they call.</h1><p>Every shopper moves inward as their buying intent rises. The center is where your attention belongs.</p></div><div className="crmStats"><article><strong>{leads.length}</strong><span>SHOPPERS</span></article><article><strong>{active}</strong><span>ACTIVE NOW</span></article><article><strong>{hot}</strong><span>HOT</span></article><article><strong>{ranked[0]?.lead_score||0}</strong><span>TOP INTENT</span></article></div></section>
{view==='radar'&&<section className="orbitLayout"><div className="orbitStage"><div className="orbitRing r1"/><div className="orbitRing r2"/><div className="orbitRing r3"/><div className="orbitCore"><span>JON</span><small>HOT ZONE</small></div><div className="orbitLabel outer">COLD</div><div className="orbitLabel middle">WARM</div><div className="orbitLabel inner">HOT</div>{ranked.map((l,i)=><button key={l.id} style={pos(l,i,ranked.length)} className={`leadOrb ${l.temperature||''} ${selected?.id===l.id?'selected':''}`} onClick={()=>setSelected(l)} title={`${who(l)} · ${l.lead_score}`}><i/><span>{l.lead_score}</span></button>)}{leads.length===0&&<div className="orbitEmpty">{error||'Waiting for your first shopper…'}</div>}</div><aside className="heatFeed"><div className="heatFeedHead"><span>LIVE INTENT FEED</span><i>● LIVE</i></div>{ranked.slice(0,8).map((l,n)=><button key={l.id} onClick={()=>setSelected(l)}><strong>0{n+1}</strong><div><b>{who(l)}</b><p>{l.last_request||'Browsing inventory'}</p><small>{timeAgo(l.last_seen_at)}</small></div><em>{l.lead_score}</em></button>)}</aside></section>}
{view==='chats'&&<section className="liveChatDesk"><aside className="chatQueue"><div className="chatQueueHead"><span>CONVERSATIONS</span><b>RANKED BY INTENT</b></div>{ranked.map(l=><button className={selected?.id===l.id?'active':''} key={l.id} onClick={()=>setSelected(l)}><span className={`chatHeat ${l.temperature||''}`}>{l.lead_score}</span><div><b>{who(l)}</b><p>{l.last_request||'Browsing inventory'}</p><small>{timeAgo(l.last_seen_at)}</small></div></button>)}</aside><div className="chatViewer">{selected?<><header><div><span>LIVE CONVERSATION</span><h2>{who(selected)}</h2></div><strong>{selected.lead_score} INTENT</strong></header><div className="chatTranscript">{(selected.transcript||[]).length?(selected.transcript||[]).map((m:any,i:number)=><div key={i} className={`chatBubble ${m.role}`}><small>{m.role==='assistant'?'ROVER':'SHOPPER'}</small><p>{m.content}</p></div>):<div className="chatNoMessages">No conversation captured yet.</div>}</div><footer><div><span>AI READ</span><p>{selected.summary||selected.next_best_action||'Learning this shopper now.'}</p></div>{selected.phone&&<a href={`sms:${selected.phone}`}>TAKE OVER CHAT →</a>}</footer></>:<div className="chatSelect">Select a conversation from the ranked queue.</div>}</div></section>}
{view==='leads'&&<section className="crmWorkspace"><div className="crmList"><div className="crmListHead"><span>SCORE</span><span>CUSTOMER</span><span>SHOPPING SIGNAL</span><span>NEXT MOVE</span><span>STATUS</span></div>{ranked.map(l=><button className="crmLead" onClick={()=>setSelected(l)} key={l.id}><span className={`crmScore ${l.temperature||''}`}>{l.lead_score}</span><span><b>{who(l)}</b><small>{timeAgo(l.last_seen_at)}</small></span><span><b>{l.last_request||'Browsing inventory'}</b><small>{l.budget_max?`Up to $${l.budget_max.toLocaleString()}`:'Budget unknown'}</small></span><span><b>{l.next_best_action||'Review conversation'}</b></span><span className="crmStatus">{l.status}</span></button>)}</div></section>}
</main>}
