import Link from "next/link";
import "../legal.css";

export const metadata={title:"Privacy Policy | Jon Rover"};

export default function PrivacyPolicy(){return <main className="legalPage"><div className="legalShell"><Link className="legalBack" href="/">← JON ROVER</Link><p className="legalEyebrow">LEGAL</p><h1>Privacy Policy</h1><p className="legalUpdated">Effective September 10, 2026</p>
<p>This Privacy Policy explains how the Jon Rover website (the “Site”) collects, uses, and shares information when you browse the Site, use the AI concierge, ask about a vehicle, or contact Jon McGeehan.</p>
<h2>Information we collect</h2><p>We may collect information you choose to provide, including your name, phone number, email address, vehicle preferences, trade-in information, budget, timing, and the contents of messages you send through the AI concierge or other forms on the Site.</p><p>When you use the AI concierge, the Site may create a browser-based session identifier and store the conversation transcript, vehicle interests, lead status, and related follow-up information so the conversation can be associated with the same inquiry. We may also receive ordinary technical information such as IP address, browser or device type, pages visited, timestamps, and diagnostic or security logs from hosting and infrastructure providers.</p>
<h2>How we use information</h2><p>We use information to respond to inquiries, identify relevant vehicles, provide customer service, follow up about a potential purchase or lease, maintain lead and conversation history, improve the Site and concierge experience, prevent abuse, troubleshoot problems, and protect the security of the Site.</p>
<h2>AI concierge</h2><p>Messages submitted to the AI concierge are processed by automated systems to generate responses and may be transmitted to service providers that help operate the feature. The concierge may make mistakes and should not be relied on as the final source for vehicle availability, specifications, pricing, financing, incentives, taxes, fees, or transaction terms. Please confirm important information directly with Jon or Jaguar Land Rover Willow Grove.</p>
<h2>Service providers</h2><p>We may use third-party service providers for website hosting, database storage, analytics, security, communications, and artificial-intelligence processing. Those providers may process information on our behalf as needed to provide their services. The Site currently uses services that may include Vercel, Supabase, and OpenAI.</p>
<h2>Sharing of information</h2><p>We do not sell your personal information. We may share information with Jaguar Land Rover Willow Grove or personnel involved in responding to your inquiry or completing a vehicle transaction, with service providers operating the Site, when required by law, or when reasonably necessary to protect rights, safety, security, or prevent fraud or abuse.</p>
<h2>Text messages and calls</h2><p>If you provide a phone number or initiate a text message, you may receive communications related to your inquiry. Message and data rates may apply. Providing a phone number through the Site does not by itself authorize unrelated marketing messages. You may ask us to stop contacting you at any time.</p>
<h2>Data retention</h2><p>We retain information for as long as reasonably necessary to respond to inquiries, maintain business records, operate and secure the Site, resolve disputes, and comply with legal obligations. Retention periods may vary depending on the type of information and the purpose for which it was collected.</p>
<h2>Your choices</h2><p>You can choose not to provide optional personal information, although some features may then be less useful. You may request access to, correction of, or deletion of personal information associated with your inquiry, subject to applicable law and legitimate recordkeeping obligations.</p>
<h2>Children</h2><p>The Site is intended for people shopping for or researching vehicles and is not directed to children under 13. We do not knowingly collect personal information from children under 13.</p>
<h2>Security</h2><p>We use reasonable administrative and technical measures intended to protect information. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.</p>
<h2>Changes to this policy</h2><p>We may update this Privacy Policy from time to time. The effective date above will be updated when material changes are made.</p>
<h2>Contact</h2><p>For privacy questions or requests, contact Jon McGeehan through the contact options provided on the Site.</p>
<div className="legalFooter"><Link href="/terms">Terms of Service</Link><Link href="/">Back to Jon Rover</Link></div></div></main>}
