"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type Message={role:"user"|"assistant";content:string};
type VehicleContext={title:string;vin:string;price?:number|null;mileage?:number|null;exterior?:string|null;interior?:string|null;stock?:string|null};

function getSessionId(){if(typeof window==="undefined")return"";const key="jon-rover-session";let id=window.localStorage.getItem(key);if(!id){id=crypto.randomUUID();window.localStorage.setItem(key,id);}return id;}
async function capture(sessionId:string,messages:Message[]){try{const r=await fetch("/api/crm/capture",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,messages}),cache:"no-store"});const data=await r.json().catch(()=>null);if(!r.ok||data?.saved===false){console.error("CRM capture failed",r.status,data);return false;}return true;}catch(error){console.error("CRM capture error",error);return false;}}

export default function Concierge(){const[open,setOpen]=useState(false),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[messages,setMessages]=useState<Message[]>([{role:"assistant",content:"Hi — I’m Jon’s virtual assistant. Tell me what you’re looking for and I’ll help narrow the live inventory down."}]);const endRef=useRef<HTMLDivElement|null>(null);useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[messages,open]);useEffect(()=>{const openRover=()=>setOpen(true);const openVehicle=(event:Event)=>{const v=(event as CustomEvent<VehicleContext>).detail;if(!v?.title||!v?.vin){setOpen(true);return;}const facts=[v.exterior,v.interior,v.mileage!=null?`${v.mileage.toLocaleString()} miles`:null,v.stock?`stock ${v.stock}`:null].filter(Boolean).join(" · ");const intro:Message={role:"assistant",content:`You're looking at the ${v.title} — VIN ${v.vin}${facts?` · ${facts}`:""}. What would you like to know about this one?`};setMessages(current=>{const next=[...current,intro];void capture(getSessionId(),next);return next;});setOpen(true);};window.addEventListener("open-jon-rover",openRover);window.addEventListener("open-jon-rover-vehicle",openVehicle as EventListener);return()=>{window.removeEventListener("open-jon-rover",openRover);window.removeEventListener("open-jon-rover-vehicle",openVehicle as EventListener);};},[]);
async function send(e?:FormEvent){e?.preventDefault();const text=input.trim();if(!text||busy)return;const sessionId=getSessionId();const next=[...messages,{role:"user",content:text}] as Message[];setMessages(next);setInput("");setBusy(true);try{await capture(sessionId,next);const r=await fetch("/api/concierge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId,messages:next}),cache:"no-store"});const data=await r.json();const reply:Message={role:"assistant",content:data?.reply||"I hit a snag. You can text Jon directly and he’ll jump in."};const updated=[...next,reply];setMessages(updated);await capture(sessionId,updated);}catch{const reply:Message={role:"assistant",content:"I hit a snag. You can text Jon directly and he’ll jump in."};const updated=[...next,reply];setMessages(updated);await capture(sessionId,updated);}finally{setBusy(false);}}
return <><button className="conciergeLauncher" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label="Open Jon Rover concierge"><span className="conciergeDot"/>ASK JON ROVER</button>{open?<aside className="conciergePanel"><div className="conciergeHeader"><div><span className="eyebrow">JON ROVER CONCIERGE</span><strong>Find the right one.</strong></div><button onClick={()=>setOpen(false)} aria-label="Close concierge">×</button></div><div className="conciergeMessages">{messages.map((m,i)=><div key={i} className={`conciergeMessage ${m.role}`}>{m.content}</div>)}{busy?<div className="conciergeTyping"><i/><i/><i/></div>:null}<div ref={endRef}/></div><form className="conciergeForm" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about this vehicle…" aria-label="Message Jon Rover concierge"/><button type="submit" disabled={busy}>→</button></form><a className="conciergeTextJon" href={`sms:+12156087408?body=${encodeURIComponent("Hi Jon, I was using the Jon Rover concierge and wanted to talk about a vehicle.")}`}>TEXT JON DIRECTLY →</a></aside>:null}</>;
}