"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type Message={role:"user"|"assistant";content:string};

function getSessionId(){if(typeof window==="undefined")return"";const key="jon-rover-session";let id=window.localStorage.getItem(key);if(!id){id=crypto.randomUUID();window.localStorage.setItem(key,id);}return id;}

export default function Concierge(){const[open,setOpen]=useState(false),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[messages,setMessages]=useState<Message[]>([{role:"assistant",content:"Hi — I’m Jon’s virtual assistant. Tell me what you’re looking for and I’ll help narrow the live inventory down."}]);const endRef=useRef<HTMLDivElement|null>(null);useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[messages,open]);useEffect(()=>{const openRover=()=>setOpen(true);window.addEventListener("open-jon-rover",openRover);return()=>window.removeEventListener("open-jon-rover",openRover);},[]);
async function send(e?:FormEvent){e?.preventDefault();const text=input.trim();if(!text||busy)return;const next=[...messages,{role:"user",content:text}] as Message[];setMessages(next);setInput("");setBusy(true);try{const r=await fetch("/api/concierge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sessionId:getSessionId(),messages:next})});const data=await r.json();setMessages(m=>[...m,{role:"assistant",content:data?.reply||"I hit a snag. You can text Jon directly and he’ll jump in."}]);}catch{setMessages(m=>[...m,{role:"assistant",content:"I hit a snag. You can text Jon directly and he’ll jump in."}]);}finally{setBusy(false);}}
return <><button className="conciergeLauncher" onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-label="Open Jon Rover concierge"><span className="conciergeDot"/>ASK JON ROVER</button>{open?<aside className="conciergePanel"><div className="conciergeHeader"><div><span className="eyebrow">JON ROVER CONCIERGE</span><strong>Find the right one.</strong></div><button onClick={()=>setOpen(false)} aria-label="Close concierge">×</button></div><div className="conciergeMessages">{messages.map((m,i)=><div key={i} className={`conciergeMessage ${m.role}`}>{m.content}</div>)}{busy?<div className="conciergeTyping"><i/><i/><i/></div>:null}<div ref={endRef}/></div><form className="conciergeForm" onSubmit={send}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Black Defender, 3 kids, under $90k…" aria-label="Message Jon Rover concierge"/><button type="submit" disabled={busy}>→</button></form><a className="conciergeTextJon" href={`sms:+12156087408?body=${encodeURIComponent("Hi Jon, I was using the Jon Rover concierge and wanted to talk about a vehicle.")}`}>TEXT JON DIRECTLY →</a></aside>:null}</>;
}
