"use client";

import Image from "next/image";
import { FormEvent, useEffect, useRef, useState } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import InventoryBrowser from "./InventoryBrowser";
import Concierge from "./Concierge";
import TextJon from "./TextJon";

gsap.registerPlugin(ScrollTrigger);
const JON_TEXT_NUMBER="+12156087408";
const GENERAL_SMS=`sms:${JON_TEXT_NUMBER}?body=${encodeURIComponent("Hi Jon, I found you through Jon Rover and wanted some help finding a vehicle.")}`;
const reviews=[{quote:"Very knowledgeable and excellent communicator!",source:"Customer review · December 2025"},{quote:"He was attentive and patient.",source:"Customer review · April 2025"},{quote:"Definitely the best experience we've ever had at a dealership.",source:"Customer review · June 2025"},{quote:"Friendly, knowledgeable and efficient service from Jon.",source:"Customer review · September 2023"},{quote:"Sales person went above and beyond.",source:"Customer review · May 2024"},{quote:"Fast responses to all correspondences.",source:"Customer review · March 2026"},{quote:"He went above and beyond to make sure my buying experience was smooth and professional.",source:"Customer review"},{quote:"He made the process of car shopping much easier for me.",source:"Customer review"}];
export default function Home(){const heroRef=useRef<HTMLElement|null>(null),heroImageRef=useRef<HTMLDivElement|null>(null),heroCopyRef=useRef<HTMLDivElement|null>(null);const[heroRequest,setHeroRequest]=useState(""),[inventoryQuery,setInventoryQuery]=useState(""),[inventorySignal,setInventorySignal]=useState(0);
useEffect(()=>{const ctx=gsap.context(()=>{gsap.to(heroImageRef.current,{yPercent:10,scale:1.05,ease:"none",scrollTrigger:{trigger:heroRef.current,start:"top top",end:"bottom top",scrub:true}});gsap.to(heroCopyRef.current,{yPercent:-12,opacity:.3,ease:"none",scrollTrigger:{trigger:heroRef.current,start:"25% top",end:"90% top",scrub:true}});});return()=>ctx.revert();},[]);
function search(q:string){setInventoryQuery(q);setInventorySignal(v=>v+1);window.setTimeout(()=>document.getElementById("inventory")?.scrollIntoView({behavior:"smooth",block:"start"}),80);}function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(heroRequest.trim())search(heroRequest.trim());}function openRover(){window.dispatchEvent(new Event("open-jon-rover"));}
return <main><section ref={heroRef} className="hero" id="home"><div ref={heroImageRef} className="heroImage"><Image src="/hero-defender.png" alt="Land Rover Defender overlooking the mountains" fill priority sizes="100vw" style={{objectFit:"cover"}}/></div><div className="heroShade"/><header className="nav shell"><a href="#home" className="brandLockup"><span className="brand">JON ROVER</span><span className="eyebrow">JAGUAR LAND ROVER WILLOW GROVE</span></a><nav><a href="#inventory">INVENTORY</a><a href="#reviews">REVIEWS</a><a href="#about">ABOUT</a></nav><button className="pill dark navRoverButton" type="button" onClick={openRover}>ASK JON ROVER</button><button className="mobileMenuIcon" type="button" aria-label="Open menu"><span/><span/><span/></button></header><div ref={heroCopyRef} className="heroCopy shell"><p className="eyebrow heroKicker">A MORE PERSONAL WAY TO BUY</p><h1>DRIVEN<br/>BY<br className="mobileBreak"/> PEOPLE.</h1><p className="heroLead">Tell me what you want. I&apos;ll narrow the live Willow Grove inventory down to the three I&apos;d look at first.</p><form className="heroVehicleSearch" onSubmit={submit}><div className="heroVehicleSearchBar"><input value={heroRequest} onChange={e=>setHeroRequest(e.target.value)} placeholder="What are you looking for?" aria-label="What vehicle are you looking for?"/><button type="submit" aria-label="Find my matches">→</button></div></form></div><div className="mobileScrollCue"><span/>SCROLL</div></section>
<InventoryBrowser initialQuery={inventoryQuery} requestSignal={inventorySignal}/>
<section id="reviews" className="reviewsSection" aria-labelledby="reviews-title"><div className="reviewsHeader shell"><div className="reviewsTop"><div><p className="eyebrow">WHAT CUSTOMERS SAY</p><h2 id="reviews-title">A better experience, in their words.</h2></div><div className="reviewStars">★★★★★</div></div></div><div className="reviewsMarquee"><div className="reviewsTrack">{[...reviews,...reviews].map((r,i)=><article className="reviewCard" key={`${r.quote}-${i}`}><div className="reviewCardStars">★★★★★</div><blockquote>“{r.quote}”</blockquote><p>{r.source}</p></article>)}</div></div></section>
<section id="about" className="personalAbout"><div className="personalAboutInner shell"><div className="personalPortraitWrap"><img className="personalPortrait" src="https://di-uploads-pod1.dealerinspire.com/landroverwillowgrove/uploads/2018/04/IMG_0181-356x356.jpg" alt="Jon McGeehan at Land Rover Willow Grove"/></div><div className="personalAboutCopy"><p className="eyebrow">ABOUT JON</p><h2>Jon McGeehan</h2><p className="personalRole">SALES GUIDE · JAGUAR LAND ROVER WILLOW GROVE</p><p className="personalIntro">I&apos;ve spent years helping people find the right Jaguar or Land Rover without making the process feel like a typical car-buying experience. Tell me what matters to you and I&apos;ll give you straight answers and help narrow down the right options.</p><div className="personalAboutActions"><TextJon className="button dark" href={GENERAL_SMS}>TEXT JON →</TextJon><button className="textLink inventoryTextButton" type="button" onClick={()=>search("")}>VIEW INVENTORY →</button></div></div></div></section><footer className="footer shell"><div><div className="brand">JON ROVER</div><div className="eyebrow">JAGUAR LAND ROVER WILLOW GROVE</div></div><p>A more personal way to buy.</p><div style={{display:"flex",gap:"18px",alignItems:"center",flexWrap:"wrap"}}><a href="/privacy" style={{fontSize:"10px",letterSpacing:".12em",color:"inherit",textDecoration:"none"}}>PRIVACY</a><a href="/terms" style={{fontSize:"10px",letterSpacing:".12em",color:"inherit",textDecoration:"none"}}>TERMS</a><TextJon className="pill dark" href={GENERAL_SMS}>TEXT JON</TextJon></div></footer><Concierge/></main>;
}
