"use client";

import Image from "next/image";
import { FormEvent, useEffect, useRef, useState } from "react";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import InventoryBrowser from "./InventoryBrowser";
import Concierge from "./Concierge";

gsap.registerPlugin(ScrollTrigger);
const JON_TEXT_NUMBER="+12156087408";
const GENERAL_SMS=`sms:${JON_TEXT_NUMBER}?body=${encodeURIComponent("Hi Jon, I found you through Jon Rover and wanted some help finding a vehicle.")}`;
const reviews=[{quote:"Very knowledgeable and excellent communicator!",source:"Customer review · December 2025"},{quote:"He was attentive and patient.",source:"Customer review · April 2025"},{quote:"Definitely the best experience we've ever had at a dealership.",source:"Customer review · June 2025"},{quote:"Friendly, knowledgeable and efficient service from Jon.",source:"Customer review · September 2023"},{quote:"Sales person went above and beyond.",source:"Customer review · May 2024"},{quote:"Fast responses to all correspondences.",source:"Customer review · March 2026"},{quote:"He went above and beyond to make sure my buying experience was smooth and professional.",source:"Customer review"},{quote:"He made the process of car shopping much easier for me.",source:"Customer review"}];
export default function Home(){const heroRef=useRef<HTMLElement|null>(null),heroImageRef=useRef<HTMLDivElement|null>(null),heroCopyRef=useRef<HTMLDivElement|null>(null);const[condition,setCondition]=useState(""),[model,setModel]=useState(""),[budget,setBudget]=useState(""),[mustHaves,setMustHaves]=useState(""),[inventoryQuery,setInventoryQuery]=useState(""),[inventorySignal,setInventorySignal]=useState(0);
useEffect(()=>{const ctx=gsap.context(()=>{gsap.to(heroImageRef.current,{yPercent:10,scale:1.05,ease:"none",scrollTrigger:{trigger:heroRef.current,start:"top top",end:"bottom top",scrub:true}});gsap.to(heroCopyRef.current,{yPercent:-12,opacity:.3,ease:"none",scrollTrigger:{trigger:heroRef.current,start:"25% top",end:"90% top",scrub:true}});});return()=>ctx.revert();},[]);
function search(q:string){setInventoryQuery(q);setInventorySignal(v=>v+1);window.setTimeout(()=>document.getElementById("inventory")?.scrollIntoView({behavior:"smooth",block:"start"}),80);}function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const parts=[condition&&`${condition} vehicle`,model&&`model or body style: ${model}`,budget&&`budget: ${budget}`,mustHaves&&`must-haves: ${mustHaves}`].filter(Boolean);if(parts.length)search(parts.join("; "));}
return <main><section ref={heroRef} className="hero" id="home"><div ref={heroImageRef} className="heroImage"><Image src="/hero-defender.png" alt="Land Rover Defender overlooking the mountains" fill priority sizes="100vw" style={{objectFit:"cover"}}/></div><div className="heroShade"/><header className="nav shell"><a href="#home" className="brandLockup"><span className="brand">JON ROVER</span><span className="eyebrow">JAGUAR LAND ROVER WILLOW GROVE</span></a><nav><a href="#inventory">INVENTORY</a><a href="#reviews">REVIEWS</a><a href="#about">ABOUT</a></nav><a className="pill dark" href={GENERAL_SMS}>TEXT JON</a></header><div ref={heroCopyRef} className="heroCopy shell"><p className="eyebrow heroKicker">A MORE PERSONAL WAY TO BUY</p><h1>DRIVEN<br/>BY PEOPLE.</h1><p className="heroLead">Give Rover four things that matter. I&apos;ll narrow the Willow Grove inventory down to the three I&apos;d look at first.</p><form className="heroFinder" onSubmit={submit}><div className="heroFinderGrid"><label><span>01 · CONDITION</span><select value={condition} onChange={e=>setCondition(e.target.value)} aria-label="New or pre-owned"><option value="">NEW OR PRE-OWNED?</option><option value="new">NEW</option><option value="used">PRE-OWNED</option><option value="new or used">OPEN TO EITHER</option></select></label><label><span>02 · VEHICLE</span><input value={model} onChange={e=>setModel(e.target.value)} placeholder="DEFENDER, SUV, RANGE ROVER…" aria-label="Model or body style"/></label><label><span>03 · BUDGET</span><input value={budget} onChange={e=>setBudget(e.target.value)} placeholder="UNDER $85K, $1,200/MO…" aria-label="Budget"/></label><label><span>04 · MUST-HAVES</span><input value={mustHaves} onChange={e=>setMustHaves(e.target.value)} placeholder="BLACK, 7 SEATS, TAN INTERIOR…" aria-label="Must-have features"/></label></div><button className="heroFinderSubmit" type="submit">SHOW ME JON&apos;S 3 PICKS <span>→</span></button></form></div></section>
<InventoryBrowser initialQuery={inventoryQuery} requestSignal={inventorySignal}/>
<section id="reviews" className="reviewsSection" aria-labelledby="reviews-title"><div className="reviewsHeader shell"><div className="reviewsTop"><div><p className="eyebrow">WHAT CUSTOMERS SAY</p><h2 id="reviews-title">A better experience, in their words.</h2></div><div className="reviewStars">★★★★★</div></div></div><div className="reviewsMarquee"><div className="reviewsTrack">{[...reviews,...reviews].map((r,i)=><article className="reviewCard" key={`${r.quote}-${i}`}><div className="reviewCardStars">★★★★★</div><blockquote>“{r.quote}”</blockquote><p>{r.source}</p></article>)}</div></div></section>
<section id="about" className="personalAbout"><div className="personalAboutInner shell"><div className="personalPortraitWrap"><img className="personalPortrait" src="https://di-uploads-pod1.dealerinspire.com/landroverwillowgrove/uploads/2018/04/IMG_0181-356x356.jpg" alt="Jon McGeehan at Land Rover Willow Grove"/></div><div className="personalAboutCopy"><p className="eyebrow">ABOUT JON</p><h2>Jon McGeehan</h2><p className="personalRole">SALES GUIDE · JAGUAR LAND ROVER WILLOW GROVE</p><p className="personalIntro">I&apos;ve spent years helping people find the right Jaguar or Land Rover without making the process feel like a typical car-buying experience. Tell me what matters to you and I&apos;ll give you straight answers and help narrow down the right options.</p><div className="personalAboutActions"><a className="button dark" href={GENERAL_SMS}>TEXT JON →</a><button className="textLink inventoryTextButton" type="button" onClick={()=>search("")}>VIEW INVENTORY →</button></div></div></div></section><footer className="footer shell"><div><div className="brand">JON ROVER</div><div className="eyebrow">JAGUAR LAND ROVER WILLOW GROVE</div></div><p>A more personal way to buy.</p><a className="pill dark" href={GENERAL_SMS}>TEXT JON</a></footer><Concierge/></main>;
}
