import Link from "next/link";
import "../legal.css";

export const metadata={title:"Terms of Service | Jon Rover"};

export default function TermsOfService(){return <main className="legalPage"><div className="legalShell"><Link className="legalBack" href="/">← JON ROVER</Link><p className="legalEyebrow">LEGAL</p><h1>Terms of Service</h1><p className="legalUpdated">Effective September 10, 2026</p>
<p>These Terms of Service govern your use of the Jon Rover website (the “Site”). By using the Site, you agree to these Terms. If you do not agree, do not use the Site.</p>
<h2>Purpose of the Site</h2><p>The Site is a personal sales and vehicle-shopping resource operated by Jon McGeehan in connection with his work at Jaguar Land Rover Willow Grove. It is designed to help shoppers explore inventory, ask questions, and connect with Jon. The Site itself is not a dealership, lender, insurer, vehicle manufacturer, or party to any vehicle sale, lease, finance, trade-in, service, or warranty agreement.</p>
<h2>No offer or binding transaction</h2><p>Nothing displayed on the Site constitutes a binding offer, guarantee, reservation, approval, contract, or commitment to sell, lease, finance, or hold any vehicle. A transaction becomes binding only when the applicable dealership documents are completed and accepted by the appropriate parties.</p>
<h2>Inventory, pricing, and vehicle information</h2><p>Inventory, availability, mileage, colors, options, equipment, pricing, incentives, payments, taxes, fees, and other vehicle information may change without notice or may contain errors. Photos may be illustrative. You are responsible for confirming all material vehicle and transaction details directly with Jaguar Land Rover Willow Grove before relying on them or making a purchase decision.</p>
<h2>AI concierge</h2><p>The AI concierge is an automated assistant intended to help answer questions and narrow vehicle options. It may misunderstand a request, rely on incomplete information, or generate inaccurate information. AI responses are informational only and are not promises, representations, professional advice, or final dealership terms. Do not rely on the concierge for final pricing, financing, incentives, taxes, fees, legal obligations, safety information, or vehicle specifications without independent confirmation.</p>
<h2>Financing and payments</h2><p>Any financing, lease, payment, rate, affordability, or incentive information shown or discussed through the Site is illustrative unless expressly confirmed in official dealership or lender documentation. Credit approval, rates, terms, incentives, taxes, fees, and eligibility are determined by the applicable dealership, lender, manufacturer, or government authority.</p>
<h2>Trade-ins</h2><p>Any trade-in estimate, discussion, or preliminary value is not a guaranteed purchase price. Final trade value depends on inspection, condition, mileage, history, market conditions, payoff information, and dealership approval.</p>
<h2>Third-party websites and services</h2><p>The Site may link to or rely on third-party websites, inventory systems, communication tools, hosting providers, databases, and AI services. We do not control third-party services and are not responsible for their availability, content, accuracy, security, or practices. Your use of third-party services may be governed by their own terms and policies.</p>
<h2>Acceptable use</h2><p>You may use the Site only for lawful personal vehicle-shopping and communication purposes. You may not attempt to disrupt the Site, bypass security, scrape or harvest data at scale, introduce malicious code, impersonate another person, misuse contact features, or use the Site in a way that violates law or the rights of others.</p>
<h2>Intellectual property</h2><p>The Site design, copy, software, branding, and original content are protected by applicable intellectual-property laws. Jaguar, Land Rover, Range Rover, Defender, and other third-party names, logos, vehicle images, and marks belong to their respective owners. Use of third-party marks on the Site is for identification and informational purposes and does not transfer ownership.</p>
<h2>No warranties</h2><p>To the fullest extent permitted by law, the Site is provided “as is” and “as available” without warranties of any kind, express or implied, including warranties of accuracy, availability, merchantability, fitness for a particular purpose, or non-infringement.</p>
<h2>Limitation of liability</h2><p>To the fullest extent permitted by law, Jon McGeehan and the operators of the Site will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for losses arising from reliance on Site content, AI responses, unavailable or inaccurate inventory, third-party services, or interruptions to the Site. Nothing in these Terms excludes liability that cannot legally be excluded or limited.</p>
<h2>Indemnification</h2><p>To the extent permitted by law, you agree to be responsible for losses, claims, or expenses arising from your unlawful misuse of the Site, violation of these Terms, or infringement of another person’s rights.</p>
<h2>Changes and availability</h2><p>We may modify, suspend, or discontinue any part of the Site at any time. We may also update these Terms from time to time. Continued use of the Site after updated Terms are posted constitutes acceptance of the revised Terms.</p>
<h2>Governing law</h2><p>These Terms are governed by the laws of the State of New Jersey, without regard to conflict-of-law principles, except where another jurisdiction’s law is required to apply.</p>
<h2>Contact</h2><p>Questions about these Terms can be directed to Jon McGeehan through the contact options provided on the Site.</p>
<div className="legalFooter"><Link href="/privacy">Privacy Policy</Link><Link href="/">Back to Jon Rover</Link></div></div></main>}
