import { NextRequest, NextResponse } from "next/server";

const DEALER_BASE = "https://www.landroverwillowgrove.com";
const INVENTORY_URL = `${DEALER_BASE}/llm/inventory/`;
const READER_PREFIX = "https://r.jina.ai/https://";

type Vehicle = {
  title: string; condition: string; mileage: number | null; price: number | null; vin: string; url: string;
  image?: string | null; stock?: string | null; exterior?: string | null; features?: string[]; searchText?: string;
};
function num(value?: string | null) { if (!value) return null; const n=Number(value.replace(/[^0-9]/g,"")); return Number.isFinite(n)?n:null; }
function normalizeUrl(value?: string | null) { if (!value) return INVENTORY_URL; if(value.startsWith("http")) return value; return `${DEALER_BASE}${value.startsWith("/")?value:`/${value}`}`; }
function readerUrl(target:string){ return `${READER_PREFIX}${target.replace(/^https:\/\//,"")}`; }
async function fetchReader(target:string){ const r=await fetch(readerUrl(target),{cache:"no-store",headers:{Accept:"text/plain"}}); if(!r.ok) throw new Error(`Reader returned ${r.status}`); return r.text(); }
function parseReaderInventory(text:string):Vehicle[]{ const records:Vehicle[]=[]; const pattern=/\[([^\]]*(?:19|20)\d{2}[^\]]*)\]\((https?:\/\/[^)]+)\)\s*(?:\r?\n)+\s*(Certified Used|Used|New)\s*(?:\r?\n)+\s*([\d,]+)\s+miles?\s*(?:\r?\n)+\s*\$([\d,]+)\s*(?:\r?\n)+\s*VIN:\s*([A-HJ-NPR-Z0-9]{17})/gi; let m; while((m=pattern.exec(text))){ const vin=m[6].toUpperCase(); if(records.some(v=>v.vin===vin)) continue; records.push({title:m[1].replace(/\s+/g," ").trim(),url:normalizeUrl(m[2]),condition:m[3].trim(),mileage:num(m[4]),price:num(m[5]),vin,searchText:`${m[1]} ${m[3]}`.toLowerCase()}); } return records; }
function parseBudget(q:string){const m=q.match(/(?:under|below|less than|max(?:imum)?|up to|no more than)\s*\$?\s*([\d,.]+)\s*(k)?/i);if(!m)return null;let n=Number(m[1].replace(/,/g,""));if(m[2])n*=1000;return Number.isFinite(n)?n:null;}
function requestedModel(query:string){const q=query.toLowerCase();if(/range rover sport/.test(q))return"range rover sport";if(/range rover velar|\bvelar\b/.test(q))return"velar";if(/range rover evoque|\bevoque\b/.test(q))return"evoque";if(/defender 130/.test(q))return"defender 130";if(/defender 110/.test(q))return"defender 110";if(/defender 90/.test(q))return"defender 90";if(/\bdefender\b/.test(q))return"defender";if(/discovery sport/.test(q))return"discovery sport";if(/\bdiscovery\b/.test(q))return"discovery";if(/f[- ]?pace/.test(q))return"f-pace";if(/\bjaguar\b/.test(q))return"jaguar";if(/\brange rover\b/.test(q))return"range rover";return null;}
function modelMatches(v:Vehicle,model:string){const t=v.title.toLowerCase();if(model==="range rover")return t.includes("range rover")&&!t.includes("sport")&&!t.includes("velar")&&!t.includes("evoque");if(model==="f-pace")return t.includes("f-pace")||t.includes("f pace");if(model==="jaguar")return t.includes("jaguar");return t.includes(model);}
function wantsSevenSeats(q:string){return /\bthird[ -]?row\b|\b3rd[ -]?row\b|\b7[ -]?seat(?:er|s)?\b|\bseven[ -]?seat(?:er|s)?\b|\b7 passenger\b|\bseven passenger\b/i.test(q);}
function likelySevenSeat(v:Vehicle){const t=`${v.title} ${(v.features||[]).join(" ")}`.toLowerCase(); return /\b7[ -]?seat|seven[ -]?seat|third[ -]?row|3rd[ -]?row|7 passenger/.test(t)||t.includes("range rover")&&(/\blwb\b|long wheelbase/.test(t))||t.includes("defender 130")||(/\bdiscovery\b/.test(t)&&!t.includes("discovery sport"));}
function scoreVehicle(v:Vehicle,q:string){q=q.trim().toLowerCase();if(!q)return 1;const hay=`${v.title} ${v.condition} ${v.exterior||""} ${(v.features||[]).join(" ")}`.toLowerCase();let s=0;const budget=parseBudget(q);if(budget!=null&&v.price!=null)s+=v.price<=budget?20:v.price<=budget+5000?1:-30;if(/\bnew\b/i.test(q))s+=v.condition.toLowerCase()==="new"?20:-50;if(/used|pre[- ]?owned|certified|cpo/i.test(q))s+=v.condition.toLowerCase()!=="new"?20:-50;if(wantsSevenSeats(q))s+=likelySevenSeat(v)?60:-100;const colors=["black","white","green","blue","red","silver","gray","grey","brown","bronze","gold"];for(const c of colors)if(new RegExp(`\\b${c}\\b`,`i`).test(q)&&hay.includes(c))s+=12;return s;}
async function enrichVehicle(v:Vehicle):Promise<Vehicle>{try{const text=await fetchReader(v.url);const image=text.match(/!\[[^\]]*\]\((https?:\/\/[^)]+\.(?:jpg|jpeg|png|webp)(?:\?[^)]*)?)\)/i)?.[1]??null;const stock=text.match(/Stock(?: Number| #|:)?\s*[:#]?\s*([A-Z0-9-]{4,})/i)?.[1]??null;const exterior=text.match(/Exterior(?: Color)?\s*[:|]\s*([^\n|]{2,60})/i)?.[1]?.trim()??null;const features=Array.from(new Set([...text.matchAll(/(?:Feature|Equipment|Package)\s*[:|]\s*([^\n|]{3,80})/gi)].map(m=>m[1].trim()).filter(Boolean))).slice(0,8);return{...v,image,stock,exterior,features};}catch{return v;}}
export async function GET(request:NextRequest){const q=request.nextUrl.searchParams.get("q")??"";const condition=(request.nextUrl.searchParams.get("condition")??"all").toLowerCase();const limit=Math.min(Math.max(Number(request.nextUrl.searchParams.get("limit")??12)||12,1),18);try{const pageUrls=[INVENTORY_URL,`${INVENTORY_URL}?page=2`,`${INVENTORY_URL}?page=3`];const texts=await Promise.all(pageUrls.map(async u=>{try{return await fetchReader(u)}catch{return""}}));const parsed=texts.flatMap(parseReaderInventory);let unique=Array.from(new Map(parsed.map(v=>[v.vin,v])).values());if(!unique.length)return NextResponse.json({error:"Willow Grove inventory could not be read right now.",vehicles:[],count:0},{status:502});if(condition==="new")unique=unique.filter(v=>v.condition.toLowerCase()==="new");if(condition==="used")unique=unique.filter(v=>v.condition.toLowerCase()!=="new");const model=requestedModel(q);let candidates=model?unique.filter(v=>modelMatches(v,model)):unique;if(model&&!candidates.length)candidates=unique;let ranked=candidates.map(vehicle=>({vehicle,score:scoreVehicle(vehicle,q)})).sort((a,b)=>b.score-a.score||(a.vehicle.price??Infinity)-(b.vehicle.price??Infinity)).slice(0,limit).map(x=>x.vehicle);let enriched=await Promise.all(ranked.map(enrichVehicle));if(wantsSevenSeats(q)){const seven=enriched.filter(likelySevenSeat);if(seven.length) enriched=seven;}
const totalMatch=texts.join("\n").match(/([\d,]+)\s+vehicles found/i)?.[1];return NextResponse.json({total:totalMatch?Number(totalMatch.replace(/,/g,"")):unique.length,count:enriched.length,query:q,condition,vehicles:enriched,source:"Land Rover Willow Grove",syncMethod:"reader-strict-records",updatedAt:new Date().toISOString()});}catch(e){console.error("Inventory route failed",e);return NextResponse.json({error:"Live inventory is temporarily unavailable."},{status:502});}}
