import { NextRequest, NextResponse } from "next/server";

type ChatMessage={role:"user"|"assistant";content:string};
type Vehicle={title:string;condition:string;mileage:number|null;price:number|null;vin:string;url:string;image?:string|null;stock?:string|null;exterior?:string|null;interior?:string|null};

function outputText(payload:any){if(typeof payload?.output_text==="string")return payload.output_text;const out:string[]=[];for(const item of payload?.output??[])for(const part of item?.content??[])if(part?.type==="output_text"&&typeof part.text==="string")out.push(part.text);return out.join("");}
function contactFrom(text:string){const email=text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]??null;const phone=text.match(/(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/)?.[0]??null;return{email,phone};}
function scoreLead(text:string){let score=10;if(/today|tomorrow|this week|appointment|come in|test drive|available|buy|purchase|trade/i.test(text))score+=35;if(/phone|call|text|email|@|\d{3}[-.\s]\d{3}/i.test(text))score+=30;if(/budget|under \$|finance|payment|lease|cash/i.test(text))score+=15;return Math.min(score,100);}
async function saveCrm(sessionId:string,messages:ChatMessage[],query:string){const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)return;const allText=messages.map(m=>m.content).join("\n");const contact=contactFrom(allText);const payload={session_id:sessionId,last_request:query,transcript:messages,phone:contact.phone,email:contact.email,lead_score:scoreLead(allText),status:"new",last_seen_at:new Date().toISOString()};await fetch(`${url}/rest/v1/jon_rover_leads?on_conflict=session_id`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(payload)}).catch(()=>{});}

export async function POST(request:NextRequest){try{const body=await request.json();const messages=(Array.isArray(body?.messages)?body.messages:[]).filter((m:any)=>m&&["user","assistant"].includes(m.role)&&typeof m.content==="string").slice(-12) as ChatMessage[];const sessionId=String(body?.sessionId||"").slice(0,120);const latest=[...messages].reverse().find(m=>m.role==="user")?.content?.trim()||"";if(!latest)return NextResponse.json({error:"Message required"},{status:400});
const inventoryResponse=await fetch(`${request.nextUrl.origin}/api/inventory?q=${encodeURIComponent(latest)}&condition=all&limit=15`,{cache:"no-store"});const inventoryData=inventoryResponse.ok?await inventoryResponse.json():{vehicles:[]};const vehicles:Vehicle[]=Array.isArray(inventoryData?.vehicles)?inventoryData.vehicles:[];
const apiKey=process.env.OPENAI_API_KEY;if(!apiKey){await saveCrm(sessionId,messages,latest);return NextResponse.json({reply:"I can help narrow this down. Tell me the model, budget, seating needs, or color that matters most and I’ll match it against Jon’s inventory.",degraded:true});}
const compactInventory=vehicles.map(v=>({title:v.title,condition:v.condition,mileage:v.mileage,price:v.price,vin:v.vin,stock:v.stock??null,exterior:v.exterior??null,interior:v.interior??null,url:v.url}));
const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.6-luna",store:false,reasoning:{effort:"low"},instructions:`You are the Jon Rover concierge, a clearly identified virtual assistant for Jon at Jaguar Land Rover Willow Grove. Your job is to help a shopper choose a vehicle and hand the customer to Jon when useful. Be concise, warm, and conversational. Ask at most one useful question at a time. Never pretend to be Jon. Never negotiate price, promise discounts, or invent availability, equipment, seating, color, mileage, packages, price, or stock status. The supplied inventory is the only vehicle data you may state as fact. Third-row means 7 seats and should prioritize full-size Discovery, Defender 130, or verified 7-seat full-size Range Rover. A requested exterior or interior color is sticky unless no suitable option exists. Respect stated budgets; do not recommend more than $10,000 above one. If the shopper has given enough information, recommend no more than 3 supplied vehicles and explain why briefly. If information is missing, ask the single question that would most improve the match. When intent is high, invite them to have Jon text them and ask for a phone number only when appropriate.`,input:[...messages,{role:"user",content:`CURRENT LIVE INVENTORY CANDIDATES:\n${JSON.stringify(compactInventory)}\n\nRespond to my latest message using only these candidates for vehicle facts.`}]} )});
if(!response.ok){console.error("Concierge OpenAI error",response.status,await response.text());await saveCrm(sessionId,messages,latest);return NextResponse.json({reply:"I can help narrow it down. What matters most right now: model, budget, seating, or color?",degraded:true});}
const reply=outputText(await response.json()).trim()||"What matters most to you in the vehicle?";const updated=[...messages,{role:"assistant",content:reply}] as ChatMessage[];await saveCrm(sessionId,updated,latest);return NextResponse.json({reply,vehicles:compactInventory.slice(0,3)});}catch(error){console.error("Concierge route failed",error);return NextResponse.json({error:"Concierge is temporarily unavailable."},{status:500});}}
